// flow-typed signature: 4c58d29bf2ee9a4813199de3045f2cea
// flow-typed version: <<STUB>>/node-mailer_v^0.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-mailer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-mailer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-mailer/examples/server' {
  declare module.exports: any;
}

declare module 'node-mailer/lib/node-mailer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-mailer/examples/server.js' {
  declare module.exports: $Exports<'node-mailer/examples/server'>;
}
declare module 'node-mailer/index' {
  declare module.exports: $Exports<'node-mailer'>;
}
declare module 'node-mailer/index.js' {
  declare module.exports: $Exports<'node-mailer'>;
}
declare module 'node-mailer/lib/node-mailer.js' {
  declare module.exports: $Exports<'node-mailer/lib/node-mailer'>;
}
