version: "3"
services:
  frontend:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-frontend
    volumes:
      - "../frontend:/srv/app"
    ports:
      - "${frontend_port}:3000"   
  sso:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-sso
    volumes:
      - "../sso:/srv/app"
    environment: 
      sso_secret: ${secret}
  loadbalancer:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-loadbalancer
    volumes:
      - "../loadbalancer:/srv/app"
    networks:
      - front-tier
      - back-tier
    ports:
      - "${loadbalancer_port}:5030"
      - "9229:9229" #DEBUG PORT
    environment:
      loadbalancer_port: ${loadbalancer_port}
      loadbalancer_secret: ${secret}
  # mailer:
  #   build:
  #     context: ..
  #     dockerfile: ./dockerfiles/Dockerfile-mailer
  #   volumes:
  #     - "../mailer:/srv/app"
  #   networks:      
  #     - back-tier
  #   ports:
  #     - "${mailer_port}:5020"
  #     - "9229:9229" #DEBUG PORT
  # resizer:
  #   build:
  #     context: ..
  #     dockerfile: ./dockerfiles/Dockerfile-resizer
  #   volumes:
  #     - "../resizer:/srv/app"
  #   networks:      
  #     - back-tier
  #   ports:
  #     - "${resizer_port}:5040"
  #     - "9229:9229" #DEBUG PORT

networks:
  front-tier:
  back-tier: 