version: "3"
services:
  frontend:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-dev
    volumes:
    - "../frontend:/srv/app"
    networks:
      - front-tier
      - back-tier
    ports:
      - "${frontend_port}:3000" 
  sso:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-dev
    volumes:
    - "../sso:/srv/app"
    networks:
      - front-tier
      - back-tier 
    ports:
      - "${sso_port}:3001"
      # - "9229:9229" #DEBUG PORT
    environment: 
      sso_secret: ${secret}
  loadbalancer:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-dev
    volumes:
    - "../loadbalancer:/srv/app"
    networks:
      - back-tier
    ports:
      - "${loadbalancer_port}:3003"
    environment:
      loadbalancer_port: ${loadbalancer_port}
      loadbalancer_secret: ${secret}

  # mailer:
  #   build:
  #     context: ..
  #     dockerfile: ./dockerfiles/Dockerfile-dev
  #   volumes:
  #   - "../mailer:/srv/app"
  #   networks:      
  #     - back-tier
  #   ports:
  #   - "${mailer_port}:5020"
  # resizer:
  #   build:
  #     context: ..
  #     dockerfile: ./dockerfiles/Dockerfile-dev
  #   volumes:
  #   - "../loadbalancer:/srv/app"
  #   networks:      
  #     - back-tier
  #   ports:
  #   - "${resizer_port}:5040"
  

networks:
  front-tier:
  back-tier:    