version: "3"
services:
  frontend:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-frontend
    volumes:
    - "../frontend:/srv/app"
    ports:  
    - "${FRONTEND_PORT}:3000"
  sso:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-sso
    volumes:
    - "../sso:/srv/app"
