version: "3"
services:
  frontend:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-dev
    volumes:
    - "../frontend:/srv/app"
    networks:
      - front-tier
      - back-tier
    ports:
    - "${FRONTEND_PORT}:3000"
  sso:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-dev
    volumes:
    - "../sso:/srv/app"
    networks:
      - front-tier
      - back-tier 
    ports:
    - "${SSO_PORT}:3001"
    - "9229:9229"

networks:
  front-tier:
  back-tier:    