version: "3"
services:
  frontend:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-dev
    volumes:
    - "../frontend:/srv/app"
    ports:
    - "${FRONTEND_PORT}:3000"
  sso:
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile-dev
    volumes:
    - "../sso:/srv/app"
    
    ports:
    - "${SSO_PORT}:3001"
    - "9229:9229"